name: conditonal-test
run-name: Run conditional test
on: [push, workflow_dispatch]

jobs:
  test:
    runs-on: ubuntu-latest
    if: github.event_name == 'push'
    steps:
      - name: run test
        run: echo "test successful"
  test-successful:
    needs: test
    if: always()
    runs-on: ubuntu-latest
    steps:
      - name: Print job context
        run: echo ${{ needs }}
      - name: Print job context 2
        run: echo ${{ needs.test }}
      - name: Print job context 3
        run: echo ${{ needs.test.result }}
      - name: Print job context 4
        run: echo ${{ needs.test.status }}        
      - name: Fail if conditional job failed
        if: ${{ needs.test.result != 'success' }}
        run: exit 1
      - run: echo "final run"
  deployment:
    needs: test-successful
    runs-on: ubuntu-latest
    steps:
      - name: run deployment
        run: echo "running deployment"
