name: conditonal-test
run-name: Run conditional test
on: [push, workflow_dispatch]

jobs:
  test:
    runs-on: ubuntu-latest
    if: github.event_name == 'push'
    steps:
      - name: run test
        run: echo "test successful"
  test-successful:
    needs: test
    if: always()
    runs-on: ubuntu-latest
    steps:
      - name: Fail if conditional job failed
        if: ${{ needs.test.result != 'success' && needs.test.result != 'skipped' }}
        run: exit 1
      - run: echo "Tests were either intentionally skipped or successful. Continue with deployment"
  deployment:
    needs: test-successful
    runs-on: ubuntu-latest
    steps:
      - name: run deployment
        run: echo "running deployment"
