name: Deploy with optional build

on:
  workflow_dispatch:
    inputs:
      temp_image_exists:
        description: 'Whether the image exists'
        required: true
        type: boolean

jobs:
  check-image-exists:
    name: Check if image exists
    runs-on: ubuntu-latest
    outputs:
      image_exists: ${{ steps.check_image.outputs.IMAGE_EXISTS }}
    steps:
      - name: Check if image exists
        id: check_image
        run: |
            if [ ${{ github.event.inputs.temp_image_exists }} == true ]; then
                echo "Image exists"
                echo "IMAGE_EXISTS=true" >> $GITHUB_ENV
            else
                echo "Image does not exist"
                echo "IMAGE_EXISTS=false" >> $GITHUB_ENV
            fi
  build-and-push-image:
    name: Build and push image
    runs-on: ubuntu-latest
    needs: check-image-exists
    if: ${{ needs.check-image-exists.outputs.image_exists == 'false' }}
    steps:
      - name: Build and push image
        run: echo "Building and pushing image"
  deploy-mavis:
    name: Deploy Mavis on Environment
    runs-on: ubuntu-latest
    needs: build-and-push-image
#    if: ${{ needs.check-image-exists.outputs.image_exists == 'true' }}
    steps:
      - name: Deploy Mavis on Environment
        run: echo "Deploying Mavis"
