name: Test
on: [workflow_dispatch, push]

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - name: Sleep for 3 minutes
              run: sleep 180s
            - name: Print success
              run: echo "Success"
              
